spring:
  datasource:
    url: jdbc:h2:mem:personapi-local
    driverClassName: org.h2.Driver
    username: fernandovgs
    password: password

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
